### ISSUE TITLE
Dependencies not found. 

### ISSUE THREAD

**Issue by danyaljj** [sameersingh/er-visualizer#1]
@sameersingh I gave this code a little try but apparently it's missing dependencies: 

```
multirexperiments#multirexperiments_2.10;0.1
org.sameersingh.nlp_serde#nlp_serde;0.1-SNAPSHOT
```

Any chance I can get the missing deps? Or run it, without the dependencies? (like sample input) 
Also, any screenshot available? 

Thanks!

**Comment by sameersingh** [comment]
I'll commit a version soon that does not have the dependencies, and update the documentation with a complete data example and screenshot soon.

**Comment by danyaljj** [comment]
Coolio! Looking forward to it! :)

**Comment by sameersingh** [comment]
Removed unnecessary dependencies, added a working test example and screenshots.

Let me know if you have any questions!

**Comment by danyaljj** [comment]
Looks great! Thanks!
